# Generated by Django 2.0.1 on 2019-02-09 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ellipse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerX', models.PositiveIntegerField()),
                ('centerY', models.PositiveIntegerField()),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('rotation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PositionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image')),
                ('postition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.Position')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='images',
            field=models.ManyToManyField(through='mask.PositionImage', to='image.Image'),
        ),
        migrations.AddField(
            model_name='defect',
            name='elipse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.Ellipse'),
        ),
        migrations.AddField(
            model_name='defect',
            name='position_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.PositionImage'),
        ),
    ]
