# Generated by Django 2.1.5 on 2019-02-10 01:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DefectPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DefectPositionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('defect_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.DefectPosition')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Ellipse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerX', models.PositiveIntegerField()),
                ('centerY', models.PositiveIntegerField()),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('rotation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='defectposition',
            name='mask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.Mask'),
        ),
        migrations.AddField(
            model_name='defect',
            name='ellipse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.Ellipse'),
        ),
        migrations.AddField(
            model_name='defect',
            name='position_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.DefectPositionImage'),
        ),
    ]
