# Generated by Django 2.1.5 on 2019-02-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectpositionimage',
            old_name='postition',
            new_name='position',
        ),
    ]
