# Generated by Django 2.1.5 on 2019-02-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0002_auto_20190209_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectpositionimage',
            old_name='position',
            new_name='defect_position',
        ),
    ]
